---
Name: perfectcmsimagesroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    "placeholderimagecreator//$Action/$ID/$OtherID": Sunnysideup\PerfectCmsImages\Control\PlaceHolderImageCreator
